[package]
name = "wtf-format"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
wtf-ast = { path = "../wtf-ast"}
wtf-parser = { path = "../wtf-parser" }

