[package]
name = "wtf-hir"
authors = ["Marcel Garus"]
version.workspace = true
edition.workspace = true

[dependencies]
wtf-ast = { path = "../wtf-ast" }
wtf-error = { path = "../wtf-error" }
wtf-tokens = { path = "../wtf-tokens" }
