[package]
name = "test-wtf-lsp"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
wtf-parser = { path = "../wtf-parser" }
wtf-error = { path = "../wtf-error" }
wtf-hir = { path = "../wtf-hir" }