[package]
name = "wtf-encode"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
wtf-ast = { path = "../wtf-ast" }
wtf-wasm = { path = "../wtf-wasm" }
wtf-parser = { path = "../wtf-parser" }
wasmparser = "0.218.0"
