name: Examples

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  examples:
    strategy:
      fail-fast: false
      matrix:
        example:
          [
            "./examples/array.wtf",
            "./examples/conditional.wtf",
            "./examples/early_return.wtf",
            "./examples/enum.wtf",
            "./examples/loop.wtf",
            "./examples/member_access.wtf",
            "./examples/numeric.wtf",
            # Include this once type-checking is implemented:
            # "./examples/record.wtf",
            "./examples/string.wtf",
            "./examples/tests.wtf",
            "./examples/ufcs.wtf",
          ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile ${{ matrix.example }}
        working-directory: ./wtf-compiler
        run: cargo run -- build ${{ matrix.example }} -v
      - name: Run ${{ matrix.example }}
        working-directory: ./wtf-compiler
        run: cargo run -- run ${{ matrix.example }} -v
      - name: Test ${{ matrix.example }}
        working-directory: ./wtf-compiler
        run: cargo run -- test ${{ matrix.example }} -v
